[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"

# Alternative: If you want to keep secrets scanning but ignore specific keys
# [build.environment]
#   SECRETS_SCAN_OMIT_KEYS = "REACT_APP_EMAILJS_PUBLIC_KEY,REACT_APP_EMAILJS_SERVICE_ID,REACT_APP_EMAILJS_TEMPLATE_ID"
